dist: trusty
language: java
jdk:
  - oraclejdk8

script:
  - './gradlew check'
  - './gradlew sonarqube'

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"

